name: Calculator Agent

on:
  workflow_dispatch:

  issues:
    types:
      - opened
      - edited

  issue_comment:
    types:
      - created

  pull_request_review:
    types:
      - submitted

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  analyse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Agent
        env:
          GROK_API_KEY: ${{ secrets.GROK_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}

          EVENT_NAME: ${{ github.event_name }}

          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}

          COMMENT_BODY: ${{ github.event.comment.body }}

          REPO_NAME: ${{ github.repository }}
          REVIEW_STATE: ${{ github.event.review.state }}
          REVIEW_BODY: ${{ github.event.review.body }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

        run: python agent/issue_agent.py
